### ISSUE TITLE
No matching image found

### ISSUE THREAD

**Issue by henrypearce4D** [joreeves/agi2nerf#1]
No matching images found, the script finds all of the cameras and sensors in the .xml file but not the images.

Hard to say how to reproduce.

I expect the images to be found and the transforms file to have more data than;
```
    "aabb_scale": 16,
    "frames": []
```

XML attached
[cameras.zip](https://github.com/joreeves/agi2nerf/files/11263372/cameras.zip)

Screenshots
![image](https://user-images.githubusercontent.com/106480554/232820126-3984e3c4-d76c-441a-a196-58078ec411f1.png)
![image](https://user-images.githubusercontent.com/106480554/232820218-536c9cf9-0937-4ba8-87c1-47dded21cb51.png)

 - OS: Windows 10 Pro

This is the script format I used and ran cmd from the folder location of the /images folder and .xml
`C:\Users\user\Downloads\Instant-NGP-for-RTX-2000\scripts\agi2nerf.py" --xml_in "cameras.xml" --imgfolder .\images`

**Comment by joreeves** [comment]
Hi @henrypearce4D , can you confirm that there is a file named `Cam001_000001.jpg` in the images folder? Also, just want to confirm that the command is being run within the folder relative to the `images` folder. If this is the case, I would be happy to dig deeper into the issue but may require the images to reproduce. If you'd prefer not to share them here you can message me on discord [here](https://discord.gg/SKah4vuG) and I can figure out what's going on.
